version: 2
jobs:
  build:
    docker:
      - image: docker:18.09.3-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            export VCS_REF=$(git rev-parse --short HEAD)
            docker build --build-arg VCS_REF=$VCS_REF -t jlivermont/docker-base:$CIRCLE_BUILD_NUM -t jlivermont/docker-base:latest .
      - run:
          name: Push Docker image
          command: | 
            echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
            docker push jlivermont/docker-base:${CIRCLE_BUILD_NUM}
            docker push jlivermont/docker-base:latest
